export const ENV_VARS = {
    PORT: 'PORT',
};

export const MONGO_VARS = {
    MONGODB_USER: 'MONGO_DB_USER',
    MONGODB_PASSWORD: 'MONGO_DB_PASSWORD',
    MONGODB_URL: 'MONGO_DB_URL',
    MONGODB_DB: 'MONGO_DB_DB',
};
